=== LeeMo2K10/Projects/WorkSpace/Tools/XML/XSD/xsdFirstEExample/src/main/resources/input.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:integer" name="Id" maxOccurs="1"
								minOccurs="1" />
							<xs:element type="xs:string" name="First_name"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:string" name="Last_name"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:string" name="Mobile" maxOccurs="1"
								minOccurs="1" />
						</xs:sequence>

						<xs:attribute name="emp_id" type="xs:string" use="required" />
					</xs:complexType>

				</xs:element>

				<xs:element name="Employee_parent" maxOccurs="1"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="Mother_name"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:string" name="Father_name"
								maxOccurs="1" minOccurs="1" />
						</xs:sequence>

						<xs:attribute name="emp_id" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LeeMo2K10/Projects/WorkSpace/Tools/XML/XSD/xsdFirstEExample/src/main/resources/xmlinput.xml
<?xml version="1.0" encoding="UTF-8"?>

<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="input.xsd">
<Employee emp_id="BIZ_042">
<Id>001</Id>
<First_name>Joydeep</First_name>
<Last_name>Paul</Last_name>
<Mobile>9823634215</Mobile>
</Employee>
<Employee_parent emp_id="BIZ_042">
<Mother_name>Panchalee Paul</Mother_name>
<Father_name>Gopal Chandra Paul</Father_name>
</Employee_parent>
</Company>
